#!/usr/bin/env python3
"""
generate_payload.py
Reads ce_mcp_bridge.lua and writes lua_payload.h containing the full Lua
source as a C string literal (LUA_PAYLOAD) suitable for embedding in the
CE plugin DLL.

Usage:
    python3 generate_payload.py <input.lua> <output.h>
"""
import sys
import os

def escape_c_string(data: bytes) -> str:
    parts = []
    i = 0
    while i < len(data):
        b = data[i]
        if b == ord('\\'):
            parts.append('\\\\')
        elif b == ord('"'):
            parts.append('\\"')
        elif b == ord('\n'):
            parts.append('\\n"\n    "')
        elif b == ord('\r'):
            parts.append('\\r')
        elif b == ord('\0'):
            parts.append('\\0')
        elif 32 <= b < 127:
            parts.append(chr(b))
        else:
            # Use octal (always exactly 3 digits) to avoid \xHH bleeding into
            # subsequent hex characters in the string literal.
            parts.append(f'\\{b:03o}')
        i += 1
    return ''.join(parts)

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.lua> <output.h>")
        sys.exit(1)

    in_path  = sys.argv[1]
    out_path = sys.argv[2]

    with open(in_path, 'rb') as f:
        data = f.read()

    escaped = escape_c_string(data)
    size    = len(data)

    header = f"""\
/* lua_payload.h — AUTO-GENERATED by generate_payload.py. DO NOT EDIT.
 * Source: {os.path.basename(in_path)}
 * Size  : {size} bytes
 */
#ifndef LUA_PAYLOAD_H
#define LUA_PAYLOAD_H

static const char LUA_PAYLOAD[] =
    "{escaped}";

static const unsigned int LUA_PAYLOAD_SIZE = {size}u;

#endif /* LUA_PAYLOAD_H */
"""

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(header)

    print(f"[generate_payload] Wrote {out_path} ({size} bytes of Lua source embedded)")

if __name__ == '__main__':
    main()
